### ISSUE TITLE
引入后项目启动失败

### ISSUE THREAD

**Issue by yuan-mei** [LianjiaTech/retrofit-spring-boot-starter#133]
作者大大 能帮忙看下吗

java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at 
com.github.lianjiatech.retrofit.spring.boot.core.PathMatchInterceptorBdfProcessor.postProcessBeanDefinitionRegistry(PathMatchInterceptorBdfProcessor.java:28)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:122)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.ifreecomm.cm.apis.app.AppConfig.main(AppConfig.java:72)

**Comment by chentianming11** [comment]
麻烦提供一下更完整的堆栈

**Comment by yuan-mei** [comment]
> 麻烦提供一下更完整的异常堆栈


已连接到目标 VM, 地址: ''127.0.0.1:52423'，传输: '套接字''

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.9.RELEASE)

2022-10-27 09:57:49 [main] INFO  com.igcom.cm.apis.app.AppConfig - Starting AppConfig on DESKTOP-G0SL3H1 with PID 5964 (D:\code\IdeaProjects\mdcs_v3.5_platform_server\cm-api\target\classes started by zf in D:\code\IdeaProjects\mdcs_v3.5_platform_server)
2022-10-27 09:57:49 [main] INFO  com.igcom.cm.apis.app.AppConfig - The following profiles are active: dev-mix
2022-10-27 09:57:49 [main] INFO  org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext - Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2a5b3fee: startup date [Thu Oct 27 09:57:49 CST 2022]; root of context hierarchy
2022-10-27 09:57:58 [main] INFO  com.github.lianjiatech.retrofit.spring.boot.core.RetrofitClientScannerRegistrar - Scan the @RetrofitClient annotated interface using the @RetrofitScan configuration. packages=[com.igcom.cm.service]
2022-10-27 09:58:02 [main] INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode!
2022-10-27 09:58:05 [main] INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate - Multiple Spring Data modules found, entering strict repository configuration mode!
2022-10-27 09:58:06 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.github.lianjiatech.retrofit.spring.boot.core.PathMatchInterceptorBdfProcessor.postProcessBeanDefinitionRegistry(PathMatchInterceptorBdfProcessor.java:28)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:122)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.igcom.cm.apis.app.AppConfig.main(AppConfig.java:72)
Caused by: java.lang.NullPointerException: null
	at com.igcom.cm.common.helper.ApplicationContextUtil.getBean(ApplicationContextUtil.java:36)
	at com.igcom.cm.service.common.MqttFactory.<clinit>(MqttFactory.java:31)
	... 14 common frames omitted
2022-10-27 09:58:06 [main] INFO  org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@2a5b3fee: startup date [Thu Oct 27 09:57:49 CST 2022]; root of context hierarchy
与目标 VM 断开连接, 地址为: ''127.0.0.1:52423'，传输: '套接字''

进程已结束,退出代码1

**Comment by yuan-mei** [comment]
就是在 该项目上， 一引入starter 坐标后 ，项目启动就报错。 同样的springboot 版本另启个项目 就不会发生

**Comment by chentianming11** [comment]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/30620547/198192666-0a34090d-1386-4937-a3ce-4c677c748e25.png">
是这个空指针导致的吧？

**Comment by yuan-mei** [comment]
> <img alt="image" width="982" src="https://user-images.githubusercontent.com/30620547/198192666-0a34090d-1386-4937-a3ce-4c677c748e25.png">
> 
> 是这个空指针导致的吧？

恩，好像是这段代码引起的
![image](https://user-images.githubusercontent.com/97596324/198199975-2fb9b7f9-36fa-40e7-84a6-54a7ca11dd7c.png)

不知道为什么不引入starter的话，项目启动运行一点问题没有， 引入的话 就会启动不起来
