### ISSUE TITLE
RetrofitIOException乱码报错

### ISSUE THREAD

**Issue by wangyunpeng0319** [LianjiaTech/retrofit-spring-boot-starter#139]
com.github.lianjiatech.retrofit.spring.boot.exception.RetrofitIOException: CRC: actual 0xace75ff5 != expected 0xc9e75ff5, request=Request{method=GET, url=, tags={class retrofit2.Invocation=getDealerVersion() [0, [2135606]]}}
	at com.github.lianjiatech.retrofit.spring.boot.exception.RetrofitException.errorExecuting(RetrofitException.java:41)
	at com.github.lianjiatech.retrofit.spring.boot.core.BodyCallAdapterFactory$BodyCallAdapter.adapt(BodyCallAdapterFactory.java:79)

retrofit-spring-boot.version=2.2.10
spring-boot-starter-parent.version=2.6.7

**Comment by chentianming11** [comment]
这个一般跟组件无关，麻烦自行排查http请求自身问题吧。
