### ISSUE TITLE
建议@RetrofitClient增加Converter

### ISSUE THREAD

**Issue by lly835** [LianjiaTech/retrofit-spring-boot-starter#18]
项目作为客户端，会请求各类服务端，可能返回json, 可能返回xml，在@RetrofitClient里定义是最方便的

**Comment by chentianming11** [comment]
有道理👍，后续会尽快支持~

**Comment by chentianming11** [comment]
v2.1.7  Support @RetrofitClient to configure Converter

**Comment by lly835** [comment]
有问题，我希望返回String, 我用了 converterFactories = ScalarsConverterFactory.class
```
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>converter-scalars</artifactId>
            <version>2.9.0</version>
        </dependency>
```

报错
```
Caused by: java.lang.IllegalAccessException: Class com.github.lianjiatech.retrofit.spring.boot.core.RetrofitFactoryBean can not access a member of class retrofit2.converter.scalars.ScalarsConverterFactory with modifiers "private"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102) ~[na:1.8.0_251]
	at java.lang.Class.newInstance(Class.java:436) ~[na:1.8.0_251]
	at com.github.lianjiatech.retrofit.spring.boot.core.RetrofitFactoryBean.getConverterFactories(RetrofitFactoryBean.java:360) ~[retrofit-spring-boot-starter-2.1.7.jar:na]
	at com.github.lianjiatech.retrofit.spring.boot.core.RetrofitFactoryBean.getRetrofit(RetrofitFactoryBean.java:331) ~[retrofit-spring-boot-starter-2.1.7.jar:na]

```

**Comment by chentianming11** [comment]
ScalarsConverterFactory没有public的无参构造器，需要手动将其配置成spring容器的Bean
