### ISSUE TITLE
RetrofitIOException: unexpected end of stream on Connection

### ISSUE THREAD

**Issue by minhnguyenvan95** [LianjiaTech/retrofit-spring-boot-starter#24]
`
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:240) ~[okio-1.17.5.jar:na]
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215) ~[okhttp-3.12.0.jar:na]
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) ~[okhttp-3.12.0.jar:na]
	... 128 common frames omitted

`

**Comment by minhnguyenvan95** [comment]
https://stackoverflow.com/a/60628153

**Comment by minhnguyenvan95** [comment]
look like I disabled retryOnConnectionFailure
