### ISSUE TITLE
连接报错：java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by wangran99** [LianjiaTech/retrofit-spring-boot-starter#46]
连接报错，不定时出现。查了资料，说是“okhttp3连接关闭时没有释放，换okhttp就好了”，我还没试过。
错误信息：

> 
2021-01-05 15:49:42 | [34mINFO [0;39m | [1;33mpool-2-thread-1[0;39m | [1;32mokhttp3.OkHttpClient[0;39m | --> POST https://open.welink.huaweicloud.com/api/auth/v2/tickets
2021-01-05 15:49:42 | [34mINFO [0;39m | [1;33mpool-2-thread-1[0;39m | [1;32mokhttp3.OkHttpClient[0;39m | Content-Type: application/json
2021-01-05 15:49:42 | [34mINFO [0;39m | [1;33mpool-2-thread-1[0;39m | [1;32mokhttp3.OkHttpClient[0;39m | Content-Length: 103
2021-01-05 15:49:42 | [34mINFO [0;39m | [1;33mpool-2-thread-1[0;39m | [1;32mokhttp3.OkHttpClient[0;39m | Connection: close
2021-01-05 15:49:42 | [34mINFO [0;39m | [1;33mpool-2-thread-1[0;39m | [1;32mokhttp3.OkHttpClient[0;39m |
2021-01-05 15:49:42 | [34mINFO [0;39m | [1;33mpool-2-thread-1[0;39m | [1;32mokhttp3.OkHttpClient[0;39m | {
  "client_id": "20200520113800906557547",
  "client_secret": "ca838912-0eqw-4b81-9610-8262a77183aa"
}
2021-01-05 15:49:42 | [34mINFO [0;39m | [1;33mpool-2-thread-1[0;39m | [1;32mokhttp3.OkHttpClient[0;39m | --> END POST (103-byte body)
2021-01-05 15:49:45 | [34mINFO [0;39m | [1;33mpool-2-thread-1[0;39m | [1;32mokhttp3.OkHttpClient[0;39m | <-- HTTP FAILED: java.net.SocketException: Connection reset
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at sun.security.ssl.InputRecord.readFully(Unknown Source)
        at sun.security.ssl.InputRecord.read(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:219)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

**Comment by chentianming11** [comment]
可以尝试多配几个连接池看看

**Comment by chentianming11** [comment]
这个问题，我暂时没遇到过😂
